package bmm;

/**
 * 
 * Title: Basic Meta-Model (BMM)
 * 
 * Java generated by OpenEhr-html to Java XSLT by Bert Verhees
 * From BMM-document:
 * 
 * 3.1.0:. Add Basic Meta-Model (BMM) spec to LANG component.:openEHR SEC:11 May 2020
 * 
*/
