openapi: 3.0.3
info:
  title: ReferenceModel
  description: "Module which uses EMF to handle ReferenceModel creation and changes"
  contact:
    email: bert.verhees@rosa.nl
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.0.1-SNAPSHOT
externalDocs:
  url: https://bertverhees.wordpress.com/category/semantic-database/
servers:
  - url: 'https'
tags:
  - name: reference_model
    externalDocs:
      url: https://bertverhees.wordpress.com/category/semantic-database/
      description: info on this project
paths:
  /reference_model/{referencemodelname}/version/{version}:
    get:
      tags:
        - reference_model
      summary: Get a referencemodel by name and version
      operationId: getReferenceModelByNameAndversion
      parameters:
        - name: referencemodelname
          in: path
          description: name that needs to be fetched
          required: true
          schema:
            type: string
        - name: version
          in: path
          description: the version that needs to be fetched
          required: true
          schema:
            type: string
      responses:
        200:
          description: succesful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/reference_model'
        404:
          description: Referencemodel not found
          content:
            {}
        403:
          description: forbidden
          content:
            {}
        401:
          description: unauthorized
          content:
            {}
    post:
      tags:
        - reference_model
      summary: creates a referencemodel with this name and version
      operationId: createReferenceModelByNameAndversion
      parameters:
        - name: referencemodelname
          in: path
          description: name that needs to be created
          required: true
          schema:
            type: string
        - name: version
          in: path
          description: the version that needs to be fetched
          required: true
          schema:
            type: string
      responses:
        201:
          description: created
          content:
            {}
        403:
          description: forbidden
          content:
            {}
        401:
          description: unauthorized
          content:
            {}
  /referencemodel/{referencemodelname}/version/{version}/packages:
    get:
      tags:
        - packages
      summary: gets a list of all packages for this referencemodel and version
      operationId: getPackagesForReferenceModelByNameAndversion
      parameters:
        - name: referencemodelname
          in: path
          description: name that of referencemodel of which the packages need to be fetched
          required: true
          schema:
            type: string
        - name: version
          in: path
          description: the version of which the packages need to be fetched
          required: true
          schema:
            type: string
      responses:
        200:
          description: succesful operation
          content:
            application/json:
              schema:
                $ref: 'components/schemas/referencemodel/packages'
        404:
          description: Referencemodel not found
          content:
            { }
        403:
          description: forbidden
          content:
            { }
        401:
          description: unauthorized
          content:
            { }
components:
  schemas:
    # Model Access Package
    modelAccess:
      description: Access to models that have been loaded and validated from one or more schema sets.
      type: object
    schemaDescriptor:
      description: Descriptor for a schema. Contains a meta-data table of attributes obtained from a parse of the schema.
    modelMetadata:
      description: Core properties of Model, may be used in a serial representation as well, such as PSchema.
      type: object
      properties:
        rmPublisher:
          type: string
          required: true
        rmRelease:
          type: string
          required: true
    schema:
      description: Abstract parent of any persistable form of a model, e.g. PSchema.
      allOf:
        - $ref: '#/components/schemas/modelMetadata'
      properties:
        version:
          type: string
          required: true
          description: Version of model, enabling schema evolution reasoning. Persisted attribute.
    schemaState:
      description: Enumeration of processing states of a Schema used by creation and validation routines in Schema
    includeSpec:
      description: Schema inclusion structure
    # Model Structure
    modelElement:
      description: Abstract meta-type of declared model elements. A declaration is a an element of a model within a context, which defines the scope of the element. Thus, a class definition and its property and routine definitions are model elements, but Types are not, since they are derived from model elements.
    packageContainer:
      description: A model component that contains packages and classes.
    package:
      description: Abstraction of a package as a tree structure whose nodes can contain other packages and classes.         The name may be qualified if it is a top-level package.
    model:
      description: Definition of the root of a model (along with what is inherited from schemaCore).
    module:
      description: Meta-type defining a generalised module concept. Descendants define actual structure and contents.

    namedItem:
      description: base class for name and id
      type: object
      properties:
        uid:
          type: string
          format: uuid
          required: true
        name:
          type: string
          required: true
          minLength: 1

    reference_model:
      description: referencemodel object
      required: true
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
          required: true
          minLength: 1
          maxLength: 100
        version:
          type: string
          required: true
          minLength: 0
          maxLength: 32
        packages:
          type: array
          minLength: 0
          items:
            $ref: '#/components/schemas/package'
        classes:
          type: array
          minLength: 0
          items:
            $ref: '#/components/schemas/class'
    class:
      description: Class object
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
          required: true
          minLength: 1
          maxLength: 256







  
