package nl.rosa.semanticdatabase.bmm.model_access_package;

/**
 * 
 * Abstract parent of any persistable form of a BMM model, e.g.
 * P_BMM_SCHEMA.
 * 
*/
public class BmmSchemaImpl implements BmmModelMetadata{

    //***** BmmSchema *****

/* * FIELDS * */

/**
 * 
 * Version of BMM model, enabling schema evolution reasoning.
 * Persisted attribute.
 * 
*/
    private String bmm_version;

        />
    
/**
 * 
 * Inclusion list of any form of BMM model, in the form of a hash of individual include specifications, each of which at least specifies the id of another schema, and may specify a namespace via which types from the included schemas are known in this schema.
 * Persisted attribute.
 * 
*/
    private Map<String,BmmIncludeSpec> includes;

        />
    
/**
 * 
 * Generated by create_bmm_model from persisted elements.
 * 
*/
    private BmmModel bmm_model;

        />
    
/**
 * 
 * Current processing state.
 * 
*/
    private BmmSchemaState state;

        />
    
/**
 * 
 * Name of this model, if this schema is a model root point.
 * Not set for sub-schemas that are not considered models on their own.
 * 
*/
    private String model_name;

        />
    
/**
 * 
 * Name of model expressed in schema; a 'schema' usually contains all of the packages of one 'model' of a publisher.
 * A publisher with more than one model can have multiple schemas.
 * 
*/
    private String schema_name;

        />
    
/**
 * 
 * Revision of schema.
 * 
*/
    private String schema_revision;

        />
    
/**
 * 
 * Schema development lifecycle state.
 * 
*/
    private String schema_lifecycle_state;

        />
    
/**
 * 
 * Primary author of schema.
 * 
*/
    private String schema_author;

        />
    
/**
 * 
 * Description of schema.
 * 
*/
    private String schema_description;

        />
    
/**
 * 
 * Contributing authors of schema.
 * 
*/
    private List<String> schema_contributors;

        />
    
/**
 * 
 * Main validation prior to generation of bmm_model.
 * 
*/
    private  ;

        />
    
    //***** BmmModelMetadata *****

/* * FIELDS * */

/**
 * 
 * Publisher of model expressed in the schema.
 * 
*/
    private String rm_publisher;

        />
    
/**
 * 
 * Release of model expressed in the schema as a 3-part numeric, e.g.
 * "3.1.0" .
 * 
*/
    private String rm_release;

        />
    
/* * ATTRIBUTE * */

/* * POJO * */

/* * FUNCTION * */

}
