package nl.rosa.semanticdatabase.bmm.model_access_package;

/**
 * 
 * Abstract parent of any persistable form of a BMM model, e.g.
 * P_BMM_SCHEMA.
 * 
*/
public interface BmmSchema extends BmmModelMetadata {

/* * ATTRIBUTE * */

/**
 * 
 * Version of BMM model, enabling schema evolution reasoning.
 * Persisted attribute.
 * 
*/
     getBmmVersion();
    void setBmmVersion( value);

/**
 * 
 * Inclusion list of any form of BMM model, in the form of a hash of individual include specifications, each of which at least specifies the id of another schema, and may specify a namespace via which types from the included schemas are known in this schema.
 * Persisted attribute.
 * 
*/
     getIncludes();
    void setIncludes( value);

/**
 * 
 * Generated by create_bmm_model from persisted elements.
 * 
*/
    BmmModel getBmmModel();
    void setBmmModel(BmmModel value);

/**
 * 
 * Current processing state.
 * 
*/
    BmmSchemaState getState();
    void setState(BmmSchemaState value);

/**
 * 
 * Name of this model, if this schema is a model root point.
 * Not set for sub-schemas that are not considered models on their own.
 * 
*/
     getModelName();
    void setModelName( value);

/**
 * 
 * Name of model expressed in schema; a 'schema' usually contains all of the packages of one 'model' of a publisher.
 * A publisher with more than one model can have multiple schemas.
 * 
*/
     getSchemaName();
    void setSchemaName( value);

/**
 * 
 * Revision of schema.
 * 
*/
     getSchemaRevision();
    void setSchemaRevision( value);

/**
 * 
 * Schema development lifecycle state.
 * 
*/
     getSchemaLifecycleState();
    void setSchemaLifecycleState( value);

/**
 * 
 * Primary author of schema.
 * 
*/
     getSchemaAuthor();
    void setSchemaAuthor( value);

/**
 * 
 * Description of schema.
 * 
*/
     getSchemaDescription();
    void setSchemaDescription( value);

/**
 * 
 * Contributing authors of schema.
 * 
*/
     getSchemaContributors();
    void setSchemaContributors( value);

/**
 * 
 * Main validation prior to generation of bmm_model.
 * 
*/
     get();
    void set( value);

/* * FUNCTION * */

/**
 * 
 * Merge in class and package definitions from other, except where the current schema already has a definition for the given type or package.
 * 
*/
      merge();

/**
 * 
 * True when validation may be commenced.
 * 
*/
      read_to_validate();

/**
 * 
 * Identifier of this schema, used for stating inclusions and identifying files.
 * Formed as: {BMM_DEFINITIONS}.create_schema_id ( rm_publisher, schema_name, rm_release) E.g.
 * "openehr_rm_ehr_1.0.4".
 * 
*/
      schema_id();

}
