package nl.rosa.semanticdatabase.bmmdata.model_access;

import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NonNull;
import nl.rosa.semanticdatabase.bmmdata.domain.classes.BmmClass;
import nl.rosa.semanticdatabase.bmmdata.domain.model_structure.BmmModel;
import nl.rosa.semanticdatabase.bmmdata.domain.model_structure.BmmPackageContainer;

import javax.persistence.Column;
import javax.persistence.Entity;
import java.util.List;
import java.util.Map;

/**
 * Default created on 6-6-2020
 */
@Getter
@EqualsAndHashCode(callSuper = true)
@Entity
public class BmmSchema extends BmmPackageContainer implements BmmModelMetadata {
    /**
     * BmmModelMetadata
     */
    @Column(name = "rm_publisher")
    private String rmPublisher;

    @Override
    public BmmModelMetadata setRmPublisher(String rmPublisher) {
        this.rmPublisher = rmPublisher;
        return this;
    }

    @Column(name = "rm_release")
    private String rmRelease;

    @Override
    public BmmModelMetadata setRmRelease(String rmRelease) {
        this.rmRelease = rmRelease;
        return this;
    }

    /**
     * BmmDeclaration
     */
    @NonNull
    private String name;
    // Functions;
    @Override
    public Boolean isRootScope(){
        return scope.equals(this);
    }
    /**
     * 1..1
     * bmm_version: String
     * Version of BMM model, enabling schema evolution reasoning. Persisted attribute.
     */
    @NonNull
    private String bmmVersion;
    /**
     * 0..1
     * primitive_types: List<P_BMM_CLASS>
     * Primitive type definitions. Persisted attribute.
     */
    private List<BmmClass> primitiveTypes;
    /**
     * 0..1
     * class_definitions: List<P_BMM_CLASS>
     * Class definitions. Persisted attribute.
     */
    private List<BmmClass> classDefinitions;
    /**
     * 0..1
     * includes: Hash<String,BMM_INCLUDE_SPEC>
     * Inclusion list, in the form of a hash of individual include specifications,
     * each of which at least specifies the id of another schema,
     * and may specify a namespace via which types from the included schemas are known in this schema.
     * Persisted attribute.
     */
    private Map<String, BmmIncludeSpec> includes;
    /**
     * 0..1
     * bmm_schema: BMM_MODEL
     * Generated by create_bmm_schema from persisted elements.
     */
    private BmmModel bmmSchema;
    /**
     * 1..1
     * state: BMM_SCHEMA_STATE
     * Current processing state.
     */
    @NonNull
    private BmmSchemaState state;
    /**
     * 0..1
     * model_name: String
     * Name of this model, if this schema is a model root point.
     * Not set for sub-schemas that are not considered models on their own.
     */
    private String modelName;
    /**
     * 1..1
     * schema_name: String
     * Name of model expressed in schema; a 'schema' usually contains all of the packages of one 'model' of a publisher.
     * A publisher with more than one model can have multiple schemas.
     */
    @NonNull
    private String schemaName;
    /**
     * 1..1
     * schema_revision: String
     * Revision of schema.
     */
    @NonNull
    private String schemaRevision;
    /**
     * 1..1
     * schema_lifecycle_state: String
     * Schema development lifecycle state.
     */
    @NonNull
    private String schemaLifecycleState;
    /**
     * 1..1
     * schema_author: String
     * Primary author of schema.
     */
    @NonNull
    private String schemaAuthor;
    /**
     * 1..1
     * schema_description: String
     * Description of schema.
     */
    @NonNull
    private String schemaDescription;
    /**
     * 0..1
     * schema_contributors: List<String>
     * Contributing authors of schema.
     */
    private List<String> schemaContributors;
}
